--[[
  Hong Kong 97 boot/full-flow smoke for MesenCE --testrunner.

  Linux counterpart of the BizHawk script generated by tools/smoke.ps1.
  Parameters via environment (requires AllowIoOsAccess):
    SHOT   — absolute PNG output path (required)
    FRAMES — frame to screenshot at (default 150; exits at FRAMES+15)
    MODE   — boot | flow
]]

local SHOT   = assert(os.getenv("SHOT"), "SHOT env var required")
local FRAMES = tonumber(os.getenv("FRAMES") or "150")
local MODE   = os.getenv("MODE") or "boot"

local frame = 0

local function wanted_input(n)
  local one, right = false, false
  if MODE == "flow" then
    -- Repeated short edges traverse language, three stories and five intro
    -- pages; once gameplay is reached, move and fire to prove live input.
    one = n >= 40 and n < 700 and (n % 55) < 4
    if n >= 700 then
      right = true
      one = (n % 20) < 3
    end
  end
  return { one = one, two = false, left = false, right = right,
           up = false, down = false }
end

local function on_input_polled()
  emu.setInput(wanted_input(frame), 0)
end

local SHOT_AT = FRAMES

local function on_end_frame()
  frame = frame + 1
  if frame == SHOT_AT then
    local png = emu.takeScreenshot()
    local f = assert(io.open(SHOT, "wb"))
    f:write(png)
    f:close()
  end
  if frame >= SHOT_AT + 15 then
    emu.stop(0)
  end
end

emu.addEventCallback(on_input_polled, emu.eventType.inputPolled)
emu.addEventCallback(on_end_frame, emu.eventType.endFrame)
