--[[
  Hong Kong 97 boot/full-flow/cheat smoke for MesenCE --testrunner.

  Linux counterpart of the BizHawk script generated by tools/smoke.ps1.
  Parameters via environment (requires AllowIoOsAccess):
    SHOT   — absolute PNG output path (required)
    FRAMES — frame to screenshot at (default 150; exits at FRAMES+15)
    MODE   — boot | flow | cheat
]]

local SHOT   = assert(os.getenv("SHOT"), "SHOT env var required")
local FRAMES = tonumber(os.getenv("FRAMES") or "150")
local MODE   = os.getenv("MODE") or "boot"
local PHASE_ADDR = tonumber(os.getenv("PHASE_ADDR") or "", 16)
local MEM = emu.memType.smsMemory

local frame = 0
local saw_target = false
local target_frame = nil
local cheat_sequence = {
  "up", "up", "down", "down", "left", "right", "left", "right",
  "two", "one",
}

local function wanted_input(n)
  local input = {
    one = false, two = false, left = false, right = false,
    up = false, down = false, pause = false,
  }
  if MODE == "flow" then
    -- Repeated short Start edges leave the Start-only title and traverse the
    -- remaining presentation pages. Once gameplay is reached, move and fire.
    -- Mesen names the SMS pause / Game Gear start button "pause" in the
    -- controller-specific Lua table (SmsController::GetKeyNameAssociations).
    input.pause = n >= 40 and n < 700 and (n % 55) < 4
    input.one = n >= 40 and n < 700 and (n % 55) < 4
    if n >= 700 then
      input.right = true
      input.one = (n % 20) < 3
    end
  elseif MODE == "cheat" then
    -- Asset upload plus the 15-step title fade finishes around frame 52 on
    -- the measured build. Start after that loop has sampled its baseline.
    local offset = n - 90
    if offset >= 0 and offset < #cheat_sequence * 12
       and (offset % 12) < 3 then
      input[cheat_sequence[math.floor(offset / 12) + 1]] = true
    end
  end
  return input
end

local function on_input_polled()
  emu.setInput(wanted_input(frame), 0)
end

local SHOT_AT = FRAMES

local function save_screenshot()
  local png = emu.takeScreenshot()
  local f = assert(io.open(SHOT, "wb"))
  f:write(png)
  f:close()
end

local function on_end_frame()
  frame = frame + 1
  local expected_phase = MODE == "cheat" and 4 or 2
  if PHASE_ADDR and emu.read(PHASE_ADDR, MEM) == expected_phase then
    saw_target = true
    target_frame = target_frame or frame
  end

  if MODE == "flow" or MODE == "cheat" then
    -- Capture while the requested phase is live, after the renderer has had
    -- time to draw several frames. The fixed timeout is the failure boundary.
    if target_frame and frame == target_frame + 30 then
      save_screenshot()
    end
    if target_frame and frame >= target_frame + 45 then
      emu.stop(0)
    elseif frame >= SHOT_AT + 15 and not saw_target then
      emu.log("FAIL: requested runtime phase was never observed")
      emu.stop(1)
    end
  else
    if frame == SHOT_AT then
      save_screenshot()
    elseif frame >= SHOT_AT + 15 then
      emu.stop(0)
    end
  end
end

emu.addEventCallback(on_input_polled, emu.eventType.inputPolled)
emu.addEventCallback(on_end_frame, emu.eventType.endFrame)
