#!/usr/bin/env python3
"""Generate src/game_tables.h with the gameplay tables read from the ROM
and the animation metadata (durations/hitboxes) from docs/anims.json.

Addresses: see docs/mapping.md.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from hk97 import load_rom, lorom

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "game_tables.h"


def read_until_ff(rom: bytes, addr24: int) -> list[int]:
    o = lorom(addr24)
    out = []
    while rom[o] != 0xFF:
        out.append(rom[o])
        o += 1
    return out


def read_bytes(rom: bytes, addr24: int, n: int) -> list[int]:
    o = lorom(addr24)
    return list(rom[o:o + n])


def read_words(rom: bytes, addr24: int, n: int) -> list[int]:
    o = lorom(addr24)
    return [rom[o + i * 2] | rom[o + i * 2 + 1] << 8 for i in range(n)]


def carr(name: str, vals, typ="u8", perline=12) -> str:
    lines = [f"static const {typ} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), perline):
        lines.append("    " + ", ".join(str(v) for v in vals[i:i + perline])
                     + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    rom = load_rom()
    parts = ["// GENERATED by tools/gen_tables.py - do not edit by hand.",
             "// Gameplay tables extracted from the original ROM (docs/mapping.md).",
             "#ifndef GAME_TABLES_H", "#define GAME_TABLES_H", ""]

    # spawner: type sequence ($AA54, FF-terminated, value+2 = real type)
    parts.append(carr("SPAWN_TYPE_SEQ", read_until_ff(rom, 0x80AA54)))
    # spawner: (delay, param) pairs at $AA67
    o = lorom(0x80AA67)
    pairs = []
    while rom[o] != 0xFF:
        pairs.append((rom[o], rom[o + 1]))
        o += 2
    parts.append(carr("SPAWN_DELAY", [p[0] for p in pairs]))
    parts.append(carr("SPAWN_PARAM", [p[1] for p in pairs]))
    # X positions of the special type (table $AA40, words until FFFF)
    xs = []
    o = lorom(0x80AA40)
    while True:
        v = rom[o] | rom[o + 1] << 8
        if v == 0xFFFF:
            break
        xs.append(v)
        o += 2
    parts.append(carr("SPAWN9_X", xs, "u16"))
    # type-3 oscillation ($A6C4, 28 bytes, signed in the logic)
    parts.append(carr("WOBBLE3", read_bytes(rom, 0x80A6C4, 0x1C)))
    # type-4 X pattern ($A73F, signed words, 0 = restart)
    ws = []
    o = lorom(0x80A73F)
    while True:
        v = rom[o] | rom[o + 1] << 8
        ws.append(v - 0x10000 if v >= 0x8000 else v)
        o += 2
        if v == 0:
            break
    parts.append(carr("ZIGZAG4", ws, "s16"))
    # boss descent ($A4B7, 0x20 signed bytes)
    parts.append(carr("BOSS_DESC", [b - 256 if b >= 128 else b
                                    for b in read_bytes(rom, 0x80A4B7, 0x20)],
                      "s8"))
    # item drops ($AF41, FF-terminated; 0 = nothing, else type = v+6)
    parts.append(carr("ITEM_DROPS", read_until_ff(rom, 0x80AF41)))
    # large-explosion offsets ($A0FC, 0x18 signed word pairs)
    offs = read_words(rom, 0x80A0FC, 0x18 * 2)
    parts.append(carr("BIGEXP_OFF",
                      [v - 0x10000 if v >= 0x8000 else v for v in offs],
                      "s16"))
    # menu cursor ($BD01: step?, n, then X,Y pairs)
    cur = read_bytes(rom, 0x80BD01, 2 + 4 * 2)
    parts.append(carr("MENU_CURSOR", cur))

    # ---- anims (per-frame durations)
    meta = json.loads((ROOT / "docs" / "anims.json").read_text())["shared"]
    for a in sorted(meta["anims"], key=int):
        frames = meta["anims"][a]
        durs = [f["dur"] for f in frames]
        parts.append(carr(f"ANIMDUR_{int(a):02X}", durs))
    nums = sorted(int(a) for a in meta["anims"])
    parts.append("static const u8* const ANIM_DURS[] = {")
    parts.append("    " + ", ".join(f"ANIMDUR_{a:02X}" for a in nums) + ",")
    parts.append("};")
    parts.append(carr("ANIM_NFRAMES",
                      [len(meta["anims"][str(a)]) for a in nums]))
    # per-anim hitboxes (frame 0), exact edges from $8088E9 (table [$3E]):
    #   b3 (X): left = ((b3&0xF)+1)*8;  right  = (b3>>4)*8 + 8
    #   b4 (Y): top  = ((b4&0xF)+2)*8;  bottom = (b4>>4)*8
    hb_l, hb_r, hb_t, hb_b = [], [], [], []
    for a in nums:
        f0 = meta["anims"][str(a)][0]
        ho = f0["hb_off"]
        b3, b4 = ho & 0xFF, ho >> 8
        hb_l.append(((b3 & 0xF) + 1) * 8)
        hb_r.append((b3 >> 4) * 8 + 8)
        hb_t.append(((b4 & 0xF) + 2) * 8)
        hb_b.append((b4 >> 4) * 8)
    parts.append(carr("ANIM_HB_L", hb_l))
    parts.append(carr("ANIM_HB_R", hb_r))
    parts.append(carr("ANIM_HB_T", hb_t))
    parts.append(carr("ANIM_HB_B", hb_b))

    parts += ["", "#endif // GAME_TABLES_H", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="ascii")
    print(f"{OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
